export const TASKS_ACTIONS = {
    FETCH_TASK: "FETCH_TASKS",
    DELETE_TASK: "DELETE_TASK",
    ADD_TASK: "ADD_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    SELECT_TASK: "SELECT_TASK",
    ACTIVE_TASK: "ACTIVE_TASK",
    SET_FILTERED_TASKS: "SET_FILTERED_TASKS"
}