export const TASKS_ACTIONS = {
    FETCH_TASK: "FETCH_TASKS",
    DELETE_TASK: "DELETE_TASK",
    ADD_TASK: "ADD_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    SELECT_TASK: "SELECT_TASK"
}

export const HIGH_PRIORITY_TASKS_ACTIONS = {
    SET_HIGH_PRIORITY_TASK: "SET_HIGH_PRIORITY_TASK"
}